begin;
select plan(15);
select has_table('public', 'mission_implementations', 'implementation table exists');
select has_table('public', 'mission_evidence', 'evidence table exists');
select row_security_active('public', 'mission_implementations', 'implementations have RLS');
select row_security_active('public', 'mission_evidence', 'evidence has RLS');
select col_is_unique('public', 'mission_implementations', 'mission_id', 'one implementation per mission');
select col_is_unique('public', 'mission_evidence', 'mission_id', 'one evidence per mission');
select has_function('public', 'save_mission_implementation', array['uuid','text','date','boolean'], 'implementation function exists');
select has_function('public', 'submit_mission_evidence_and_advance', array['uuid','text','text','date'], 'transition function exists');
select has_column('public', 'missions', 'completed_at', 'missions record completion time');
select has_column('public', 'missions', 'completed_by', 'missions record completing owner');
select has_index('public', 'mission_implementations_organization_id_idx', 'implementation organization indexed');
select has_index('public', 'mission_evidence_organization_id_idx', 'evidence organization indexed');
select has_check('public', 'missions', 'missions_status_check', 'mission status remains constrained');
select has_check('public', 'missions', 'missions_completion_check', 'mission completion metadata constrained');
select has_trigger('public', 'tool_instances', 'prevent_confirmed_tool_change', 'confirmed tool becomes immutable');
select * from finish();
rollback;
