"use client";

import { useState } from "react";
import type { CrmOpportunity, InternalRole } from "@/modules/crm/domain";

type Workspace = { offers: { id: string; code: string; name: string; price_version_id: string; amount: number; currency_code: string }[]; proposals: { id: string; status: string; amount: number; currency_code: string; expires_on: string | null; opportunity_title: string; account_name: string }[] };
export function OpsFinanceConsole({ opportunities, roles, workspace }: { opportunities: CrmOpportunity[]; roles: InternalRole[]; workspace: Workspace }) {
  const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false);
  const canManage = roles.includes("admin") || roles.includes("finance"); const canPropose = canManage || roles.includes("commercial");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); setMessage(null); try { const action = String(form.get("action")); const payload = action === "createOffer" ? { action, code: form.get("code"), name: form.get("name"), amount: form.get("amount"), currency: "BRL" } : action === "createProposal" ? { action, opportunityId: form.get("opportunityId"), priceVersionId: form.get("priceVersionId"), expiresOn: form.get("expiresOn") || null } : { action, proposalId: form.get("proposalId"), dueOn: form.get("dueOn") || null, methodLabel: form.get("methodLabel") || null, externalReference: form.get("externalReference") || null }; const response = await fetch("/api/ops/finance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error("request_failed"); setMessage("Registro financeiro realizado e auditado. Atualize a página para consultar o estado consolidado."); event.currentTarget.reset(); } catch { setMessage("Não foi possível concluir esta operação financeira."); } finally { setPending(false); } }
  if (!canPropose) return null;
  return <section className="ops-finance"><header><p className="eyebrow">Receita controlada · homologação</p><h2>Propostas e elegibilidade</h2><p className="summary">Sem checkout, cartão, PIX ou integração externa. A confirmação manual não altera automaticamente acessos de membros.</p></header>{canManage && <details><summary>+ Nova oferta e preço</summary><form className="auth-form" onSubmit={submit}><input type="hidden" name="action" value="createOffer" /><label>Código<input name="code" placeholder="mesa-anual" required /></label><label>Oferta<input name="name" required /></label><label>Preço (BRL)<input name="amount" type="number" min="0" step="0.01" required /></label><button disabled={pending}>Criar oferta</button></form></details>}{canPropose && <details><summary>+ Nova proposta</summary><form className="auth-form" onSubmit={submit}><input type="hidden" name="action" value="createProposal" /><label>Oportunidade<select name="opportunityId" required>{opportunities.map((opportunity) => <option key={opportunity.id} value={opportunity.id}>{opportunity.account_name} · {opportunity.title}</option>)}</select></label><label>Oferta / preço<select name="priceVersionId" required>{workspace.offers.map((offer) => <option key={offer.price_version_id} value={offer.price_version_id}>{offer.name} · {new Intl.NumberFormat("pt-BR", { style: "currency", currency: offer.currency_code }).format(offer.amount)}</option>)}</select></label><label>Validade<input name="expiresOn" type="date" /></label><button disabled={pending || !workspace.offers.length || !opportunities.length}>Criar proposta</button></form></details>}<section className="ops-finance-list"><h3>Propostas da sua função</h3>{workspace.proposals.length ? <ul>{workspace.proposals.map((proposal) => <li key={proposal.id}><strong>{proposal.account_name}</strong> · {proposal.opportunity_title}<br />{new Intl.NumberFormat("pt-BR", { style: "currency", currency: proposal.currency_code }).format(proposal.amount)} · {proposal.status}{canManage && <form className="auth-form" onSubmit={submit}><input type="hidden" name="action" value="confirmPayment" /><input type="hidden" name="proposalId" value={proposal.id} /><label>Vencimento<input name="dueOn" type="date" /></label><label>Método (sem dados sensíveis)<input name="methodLabel" maxLength={80} placeholder="Ex.: confirmação manual" /></label><label>Referência externa (opcional)<input name="externalReference" maxLength={160} /></label><button className="button-quiet" disabled={pending}>Confirmar pagamento</button></form>}</li>)}</ul> : <p className="feedback">Nenhuma proposta disponível.</p>}</section>{message && <p className="feedback" role="status">{message}</p>}</section>;
}
