"use client";
import { useActionState, useState } from "react";
import { invalidateTutorIAMemory, saveTutorIAMemory } from "./actions";
import { memoryKindLabels, memoryKinds, type TutorIAMemory } from "./domain";

const initial = { status: "idle" as const };
export function TutorIAMemoryPanel({ memories }: { memories: TutorIAMemory[] }) {
  const [editing, setEditing] = useState<TutorIAMemory | null>(null); const [state, action, pending] = useActionState(saveTutorIAMemory, initial);
  return <section className="ai-budget-card tutoria-memory-card" aria-labelledby="tutoria-memory-title"><div><p className="eyebrow">Contexto do TutorIA</p><h2 id="tutoria-memory-title">O que a TutorIA pode lembrar</h2><p>Registre apenas informações úteis para sua jornada. Conversas não são armazenadas automaticamente e você pode corrigir ou invalidar qualquer item.</p></div>
    <form action={action} className="ai-budget-form"><input type="hidden" name="memoryId" value={editing?.id ?? ""} /><label>Tipo<select name="kind" defaultValue={editing?.kind ?? "decision"} key={editing?.id ?? "new"}>{memoryKinds.map((kind) => <option key={kind} value={kind}>{memoryKindLabels[kind]}</option>)}</select></label><label>Informação confirmada<textarea name="content" defaultValue={editing?.content ?? ""} key={`${editing?.id ?? "new"}-content`} minLength={3} maxLength={2000} required /></label><label>Confiança (1–100)<input name="confidence" type="number" min="1" max="100" defaultValue={editing?.confidence ?? 100} key={`${editing?.id ?? "new"}-confidence`} required /></label><button type="submit" disabled={pending}>{pending ? "Salvando…" : editing ? "Salvar correção" : "Registrar no meu contexto"}</button>{editing && <button type="button" className="button-secondary" onClick={() => setEditing(null)}>Cancelar edição</button>}{state.message && <p className={`feedback feedback-${state.status}`} role="status">{state.message}</p>}</form>
    <div className="ai-budget-history"><strong>Memórias ativas</strong>{memories.filter((memory) => memory.state === "active").length ? <ul>{memories.filter((memory) => memory.state === "active").map((memory) => <li key={memory.id}><b>{memoryKindLabels[memory.kind]}:</b> {memory.content} <small>· confirmada por você · v{memory.version} · confiança {memory.confidence}%</small><span><button type="button" className="header-action" onClick={() => setEditing(memory)}>Corrigir</button><form action={invalidateTutorIAMemory}><input type="hidden" name="memoryId" value={memory.id} /><button type="submit" className="header-action">Invalidar</button></form></span></li>)}</ul> : <p>Nenhuma memória confirmada ainda. O TutorIA seguirá usando apenas os dados estruturados da sua jornada.</p>}</div>
  </section>;
}
