"use client";
import { useState, type ReactNode } from "react";

type Result = { code?: string; orientation?: { resumo: string; proxima_acao: string; justificativa_metodologica: string } };
const messages: Record<string, string> = { orientation_unavailable: "A orientação está em homologação e ainda não está disponível neste ambiente.", orientation_budget_unavailable: "O TutorIA não está disponível porque a política de orçamento ainda não foi configurada.", orientation_rate_limited: "Você fez muitas tentativas agora. Aguarde um instante e tente novamente.", orientation_escalated: "Para orientar com segurança, preciso de mais contexto ou de apoio humano.", unsupported_request: "Posso ajudar com gestão, decisões, finanças, equipe, vendas, processos e sua jornada na Mesa." };

export function TutorIAAssistant({ workbench }: { workbench?: ReactNode }) {
  const [open, setOpen] = useState(false); const [question, setQuestion] = useState(""); const [result, setResult] = useState<Result | null>(null); const [pending, setPending] = useState(false);
  async function ask() { setPending(true); setResult(null); try { const response = await fetch("/api/tutoria/orientation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ objective: "understand_next_step", question }) }); setResult(await response.json()); } catch { setResult({ code: "orientation_unavailable" }); } finally { setPending(false); } }
  return <><button type="button" className="floating-tutoria" aria-label="TutorIA" aria-expanded={open} aria-controls="tutoria-assistant" onClick={() => setOpen((value) => !value)}><span aria-hidden="true">IA</span><strong>TutorIA</strong></button>{open && <section id="tutoria-assistant" className="tutoria-assistant" aria-labelledby="tutoria-assistant-title"><header><div><p className="eyebrow">TutorIA</p><h2 id="tutoria-assistant-title">Vamos pensar juntos</h2><p>Estou considerando sua jornada e o contexto disponível para orientar você.</p></div><button type="button" className="tutoria-close" aria-label="Fechar conversa TutorIA" onClick={() => setOpen(false)}>×</button></header><div className="tutoria-conversation">{result?.orientation && <article className="tutoria-answer"><strong>{result.orientation.resumo}</strong><p>{result.orientation.proxima_acao}</p><small>{result.orientation.justificativa_metodologica}</small></article>}{result?.code && <p className="tutoria-state" role="status">{messages[result.code] ?? "Não foi possível orientar agora. Tente novamente em instantes."}</p>}</div><div className="tutoria-composer"><label className="sr-only" htmlFor="tutoria-question">Mensagem para a TutorIA</label><textarea id="tutoria-question" value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={1200} placeholder="Conte o que está acontecendo ou pergunte o que precisa decidir…" onKeyDown={(event) => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") void ask(); }} /><button type="button" onClick={ask} disabled={pending || question.trim().length < 4}>{pending ? "Analisando…" : "Enviar"}</button></div>{workbench && <details className="tutoria-workbench-disclosure"><summary>Abrir ferramenta com a TutorIA</summary>{workbench}</details>}</section>}</>;
}
