"use client";
import { useState } from "react";

type Result = { code?: string; orientation?: { resumo: string; proxima_acao: string; justificativa_metodologica: string } };
const messages: Record<string, string> = { orientation_unavailable: "A orientação está em homologação e ainda não está disponível neste ambiente.", orientation_budget_unavailable: "O TutorIA não está disponível porque a política de orçamento ainda não foi configurada.", orientation_rate_limited: "Você fez muitas tentativas agora. Aguarde um instante e tente novamente.", orientation_escalated: "Para orientar com segurança, preciso de mais contexto ou de apoio humano.", unsupported_request: "Posso ajudar com gestão, decisões, finanças, equipe, vendas, processos e sua jornada na Mesa." };

export function TutorIAAssistant() {
  const [question, setQuestion] = useState(""); const [objective, setObjective] = useState<"understand_next_step" | "understand_methodology">("understand_next_step"); const [result, setResult] = useState<Result | null>(null); const [pending, setPending] = useState(false);
  async function ask() { setPending(true); setResult(null); try { const response = await fetch("/api/tutoria/orientation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ objective, question }) }); setResult(await response.json()); } catch { setResult({ code: "orientation_unavailable" }); } finally { setPending(false); } }
  return <section id="tutoria-assistant" className="tutoria-assistant" aria-labelledby="tutoria-assistant-title"><div><p className="eyebrow">TutorIA</p><h2 id="tutoria-assistant-title">Vamos pensar juntos</h2><p>Traga uma dúvida real de gestão. O TutorIA orienta, não decide ou executa por você.</p></div><div className="tutoria-assistant-form"><label htmlFor="tutoria-objective">Como posso ajudar?</label><select id="tutoria-objective" value={objective} onChange={(event) => setObjective(event.target.value as typeof objective)}><option value="understand_next_step">Entender meu próximo passo</option><option value="understand_methodology">Entender a metodologia</option></select><label htmlFor="tutoria-question">Sua pergunta</label><textarea id="tutoria-question" value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={1200} placeholder="Ex.: Não sei o que é DRE. Por onde começo?" /><button type="button" onClick={ask} disabled={pending || question.trim().length < 4}>{pending ? "Analisando…" : "Pedir orientação"}</button>{result?.orientation && <article className="tutoria-answer"><strong>{result.orientation.resumo}</strong><p>{result.orientation.proxima_acao}</p><small>{result.orientation.justificativa_metodologica}</small></article>}{result?.code && <p className="tutoria-state" role="status">{messages[result.code] ?? "Não foi possível orientar agora. Tente novamente em instantes."}</p>}</div></section>;
}
