"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";

type Result = { code?: string; orientation?: { resumo: string; proxima_acao: string; justificativa_metodologica: string } };
type ConversationEntry = { role: "member"; body: string } | { role: "tutoria"; result?: Result; body?: string };
const messages: Record<string, string> = { orientation_unavailable: "A orientação está em homologação e ainda não está disponível neste ambiente.", orientation_budget_unavailable: "O TutorIA não está disponível porque a política de orçamento ainda não foi configurada.", orientation_rate_limited: "Você fez muitas tentativas agora. Aguarde um instante e tente novamente.", orientation_escalated: "Para orientar com segurança, preciso de mais contexto ou de apoio humano.", unsupported_request: "Posso ajudar com gestão, decisões, finanças, equipe, vendas, processos e sua jornada na Mesa." };
const conversationStorageKey = "mesa-os:tutoria:conversation:v1";

export function TutorIAAssistant({ workbench }: { workbench?: ReactNode }) {
  const [open, setOpen] = useState(false); const [question, setQuestion] = useState(""); const [result, setResult] = useState<Result | null>(null); const [conversation, setConversation] = useState<ConversationEntry[]>([]); const [pending, setPending] = useState(false); const [supportPending, setSupportPending] = useState(false); const [supportState, setSupportState] = useState<"idle" | "sent" | "failed">("idle"); const [conversationRestored, setConversationRestored] = useState(false); const restoreTimer = useRef<number | null>(null);
  useEffect(() => { restoreTimer.current = window.setTimeout(() => { try { const saved = window.sessionStorage.getItem(conversationStorageKey); if (saved) { const parsed = JSON.parse(saved) as { question?: unknown; result?: Result | null; conversation?: unknown }; if (typeof parsed.question === "string") setQuestion(parsed.question); if (Array.isArray(parsed.conversation)) setConversation(parsed.conversation.filter(isConversationEntry)); else if (parsed.result && typeof parsed.result === "object") { setResult(parsed.result); setConversation([{ role: "tutoria", result: parsed.result }]); } } void fetch("/api/tutoria/conversation").then((response) => response.ok ? response.json() : null).then((payload: { messages?: Array<{ role?: unknown; content?: unknown }> } | null) => { const messages = payload?.messages?.flatMap((message): ConversationEntry[] => message.role === "member" && typeof message.content === "string" ? [{ role: "member", body: message.content }] : message.role === "tutoria" && typeof message.content === "string" ? [{ role: "tutoria", body: message.content }] : []) ?? []; if (messages.length) setConversation(messages); }).catch(() => undefined); } catch { window.sessionStorage.removeItem(conversationStorageKey); } finally { setConversationRestored(true); } }, 0); return () => { if (restoreTimer.current !== null) window.clearTimeout(restoreTimer.current); }; }, []);
  useEffect(() => { if (!conversationRestored) return; try { if (!question && !result && !conversation.length) window.sessionStorage.removeItem(conversationStorageKey); else window.sessionStorage.setItem(conversationStorageKey, JSON.stringify({ question, result, conversation })); } catch { /* The conversation remains available in the current screen when storage is unavailable. */ } }, [conversationRestored, question, result, conversation]);
  async function ask() { const asked = question.trim(); if (asked.length < 4) return; setPending(true); setResult(null); setQuestion(""); setConversation((entries) => [...entries, { role: "member", body: asked }]); let responseBody: Result; try { const response = await fetch("/api/tutoria/orientation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ objective: "understand_next_step", question: asked }) }); responseBody = await response.json(); } catch { responseBody = { code: "orientation_unavailable" }; } finally { setPending(false); } setResult(responseBody); setConversation((entries) => [...entries, { role: "tutoria", result: responseBody }]); }
  async function requestHumanSupport() { const latestMemberMessage = [...conversation].reverse().find((entry) => entry.role === "member"); setSupportPending(true); setSupportState("idle"); try { const response = await fetch("/api/support", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "open", category: "other", subject: "Apoio solicitado pelo TutorIA", message: latestMemberMessage?.role === "member" ? latestMemberMessage.body : "O membro solicitou apoio humano pela conversa com a TutorIA." }) }); setSupportState(response.ok ? "sent" : "failed"); } catch { setSupportState("failed"); } finally { setSupportPending(false); } }
  function clearConversation() { setQuestion(""); setResult(null); setConversation([]); setSupportState("idle"); try { window.sessionStorage.removeItem(conversationStorageKey); } catch { /* Nothing else is required when browser storage is unavailable. */ } }
  const needsHumanSupport = result?.code === "orientation_escalated";
  return <><button type="button" className="floating-tutoria" aria-label="TutorIA" aria-expanded={open} aria-controls="tutoria-assistant" onClick={() => setOpen((value) => !value)}><span aria-hidden="true">IA</span><strong>TutorIA</strong></button>{open && <section id="tutoria-assistant" className="tutoria-assistant" aria-labelledby="tutoria-assistant-title"><header><div><p className="eyebrow">TutorIA</p><h2 id="tutoria-assistant-title">Vamos pensar juntos</h2><p>Estou considerando sua jornada e o contexto disponível para orientar você.</p></div><div className="tutoria-header-actions">{(question || conversation.length > 0) && <button type="button" className="tutoria-reset" onClick={clearConversation}>Nova conversa</button>}<button type="button" className="tutoria-close" aria-label="Fechar conversa TutorIA" onClick={() => setOpen(false)}>×</button></div></header><div className="tutoria-conversation">{conversation.map((entry, index) => entry.role === "member" ? <p key={index} className="tutoria-member-message">{entry.body}</p> : <TutorIAResponse key={index} result={entry.result} body={entry.body} />)}{needsHumanSupport && <div className="tutoria-human-support"><p>Se preferir, encaminho esta conversa para a equipe certa.</p><button type="button" onClick={() => void requestHumanSupport()} disabled={supportPending || supportState === "sent"}>{supportState === "sent" ? "Pedido encaminhado" : supportPending ? "Encaminhando…" : "Falar com a equipe"}</button>{supportState === "failed" && <small role="status">Não foi possível encaminhar agora. Tente novamente em instantes.</small>}</div>}</div><div className="tutoria-composer"><label className="sr-only" htmlFor="tutoria-question">Mensagem para a TutorIA</label><textarea id="tutoria-question" value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={1200} placeholder="Conte o que está acontecendo ou pergunte o que precisa decidir…" onKeyDown={(event) => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") void ask(); }} /><button type="button" onClick={ask} disabled={pending || question.trim().length < 4}>{pending ? "Analisando…" : "Enviar"}</button></div>{workbench && <details className="tutoria-workbench-disclosure"><summary>Abrir ferramenta com a TutorIA</summary>{workbench}</details>}</section>}</>;
}

function isConversationEntry(value: unknown): value is ConversationEntry {
  if (!value || typeof value !== "object" || !("role" in value)) return false;
  const entry = value as { role?: unknown; body?: unknown; result?: unknown };
  return (entry.role === "member" && typeof entry.body === "string") || (entry.role === "tutoria" && ((entry.result !== null && typeof entry.result === "object") || typeof entry.body === "string"));
}

function TutorIAResponse({ result, body }: { result?: Result; body?: string }) {
  if (body) return <article className="tutoria-answer"><p>{body}</p></article>;
  if (!result) return null;
  if (result.orientation) return <article className="tutoria-answer"><strong>{result.orientation.resumo}</strong><p>{result.orientation.proxima_acao}</p><small>{result.orientation.justificativa_metodologica}</small></article>;
  return <p className="tutoria-state" role="status">{messages[result.code ?? ""] ?? "Não foi possível orientar agora. Tente novamente em instantes."}</p>;
}
