import type { ReactNode } from "react";
import type { DiagnosticWorkspace } from "@/modules/diagnostic/domain/diagnostic";

export function DiagnosticsOverview({ workspace, diagnosticContent }: { workspace: DiagnosticWorkspace; diagnosticContent: ReactNode }) {
  const completed = workspace.status === "completed";
  return <section className="records-page diagnostics-page" aria-labelledby="diagnostics-title">
    <header className="records-heading"><p className="eyebrow">Medir para evoluir</p><h1 id="diagnostics-title">Diagnósticos</h1><p>O diagnóstico de entrada cria a linha de base. Novas medições só serão abertas nos marcos metodológicos autorizados.</p></header>
    <section className="diagnostic-model"><div><p className="eyebrow light">Modelo de avaliação</p><h2>Completo na entrada. Objetivo nos próximos marcos.</h2><p>A linha de base combina autopercepção estruturada com as dimensões da metodologia. Reanálises futuras permanecem protegidas até sua definição formal.</p></div><div className="diagnostic-model-steps"><span><strong>01</strong>Autopercepção</span><span><strong>02</strong>Dimensões</span><span><strong>03</strong>Evidências</span><span><strong>04</strong>Evolução</span></div></section>
    <div className="diagnostics-grid"><section className="diagnostic-timeline"><div className="records-section-title"><div><p className="eyebrow">Linha do tempo</p><h2>Momentos de reanálise</h2></div></div><div className="diagnostic-moment completed"><span>{completed ? "✓" : "1"}</span><div><small>Entrada · Mês 0</small><strong>Diagnóstico de entrada</strong><p>{completed ? "Linha de base registrada." : "Pendente de conclusão."}</p></div><b>{workspace.result?.ime ?? "—"}</b></div>{["Próxima reanálise", "Medição intermediária", "Diagnóstico de saída"].map((label, index) => <div className="diagnostic-moment future" key={label}><span>{index + 2}</span><div><small>Marco futuro</small><strong>{label}</strong><p>Aguardando autorização metodológica.</p></div><b>Protegido</b></div>)}</section>
      <aside className="diagnostic-composition"><div className="records-section-title"><div><p className="eyebrow">Reanálise trimestral</p><h2>O que será medido</h2></div></div><ol>{["Pulso de maturidade nos quatro pilares", "Indicadores definidos no início do ciclo", "Entregas e evidências realmente aprovadas", "Horas do dono e concentração de decisões", "Direção estratégica derivada pelo Raio-X"].map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol><details><summary>{completed ? "Ver diagnóstico de entrada" : "Continuar diagnóstico"}</summary><div className="diagnostic-detail-content">{diagnosticContent}</div></details></aside></div>
  </section>;
}
