"use client";

import { useEffect, useState } from "react";
import type { InternalRole } from "@/modules/crm/domain";

type Support = { id: string; organization_name: string; category: string; subject: string; status: string; source_evidence_id?: string | null; messages: { id: string; body: string; created_at: string }[] };

export function OpsSupportConsole({ roles }: { roles: InternalRole[] }) {
  const [items, setItems] = useState<Support[]>([]);
  const [unavailable, setUnavailable] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [pendingId, setPendingId] = useState<string | null>(null);
  const canResolveEvidence = roles.includes("admin") || roles.includes("mentor");
  async function load() { try { const response = await fetch("/api/ops/support"); const payload = await response.json(); if (!response.ok) throw new Error("support_unavailable"); setItems(payload.requests ?? []); setUnavailable(false); } catch { setUnavailable(true); } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function reply(form: HTMLFormElement, requestId: string) { setPendingId(requestId); setMessage(null); const data = Object.fromEntries(new FormData(form)); try { const response = await fetch("/api/ops/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId, message: data.message, status: data.status }) }); if (!response.ok) throw new Error("support_reply_failed"); form.reset(); setMessage("Resposta registrada e enviada ao membro."); await load(); } catch { setMessage("Não foi possível registrar a resposta agora. Tente novamente em instantes."); } finally { setPendingId(null); } }
  async function resolveEvidence(form: HTMLFormElement, supportId: string, evidenceId: string) { setPendingId(supportId); setMessage(null); const data = Object.fromEntries(new FormData(form)); try { const response = await fetch("/api/ops/evidence-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ evidenceId, outcome: data.outcome, rationale: data.rationale }) }); if (!response.ok) throw new Error("evidence_resolution_failed"); form.reset(); setMessage(data.outcome === "approved" ? "Evidência validada. A continuidade da Missão foi liberada." : "Complemento solicitado ao membro. O histórico foi preservado."); await load(); } catch { setMessage("Não foi possível registrar a decisão agora. Confirme seu acesso e tente novamente."); } finally { setPendingId(null); } }
  if (unavailable) return <section className="ops-finance"><header><p className="eyebrow">Apoio ao membro</p><h2>Fila de suporte indisponível</h2><p className="summary">Não foi possível carregar os casos no seu escopo. Nenhuma decisão foi alterada.</p></header><button type="button" className="button-quiet" onClick={() => void load()}>Tentar novamente</button></section>;
  return <section className="ops-finance"><header><p className="eyebrow">Apoio ao membro</p><h2>Fila de suporte</h2><p className="summary">Somente atendimentos no seu escopo. Não inclui conversas do TutorIA ou dados financeiros.</p></header>{message && <p className="feedback" role="status">{message}</p>}{items.length ? <ul className="ops-finance-list">{items.map((item) => <li key={item.id}><strong>{item.organization_name} · {item.subject}</strong><br /><small>{item.source_evidence_id ? "Evidência escalada pelo TutorIA" : item.category} · {item.status}</small>{item.messages.map((entry) => <p key={entry.id}>{entry.body}</p>)}{item.source_evidence_id && canResolveEvidence ? <form className="auth-form" onSubmit={(event) => { event.preventDefault(); void resolveEvidence(event.currentTarget, item.id, item.source_evidence_id!); }}><label>Decisão humana<select name="outcome"><option value="approved">Validar evidência</option><option value="changes_requested">Solicitar complemento</option></select></label><label>Justificativa ao membro<textarea name="rationale" minLength={20} maxLength={2000} required /></label><button disabled={pendingId === item.id}>{pendingId === item.id ? "Registrando…" : "Registrar decisão"}</button></form> : item.source_evidence_id ? <p className="feedback">A decisão metodológica será registrada por Mentor ou Admin. Você pode acompanhar o membro por esta fila.</p> : <form className="auth-form" onSubmit={(event) => { event.preventDefault(); void reply(event.currentTarget, item.id); }}><label>Resposta<textarea name="message" minLength={1} maxLength={2000} required /></label><label>Próximo estado<select name="status"><option value="waiting_member">Aguardar membro</option><option value="resolved">Resolver</option></select></label><button disabled={pendingId === item.id}>{pendingId === item.id ? "Enviando…" : "Responder"}</button></form>}</li>)}</ul> : <p className="feedback">Nenhum pedido de apoio no seu escopo.</p>}</section>;
}
