"use client";

import { useState } from "react";
import type { InternalRole } from "@/modules/crm/domain";

type Portfolio = { assignment_id: string; kind: "concierge" | "mentor"; organization_id: string; organization_name: string; assigned_at: string; active_cycle_title: string | null; active_cycle_ends_on: string | null; next_action_label: string | null; approved_milestone_count: number; onboarding_pending_enrollments: number };
type ManagedPortfolio = { assignment_id: string; organization_id: string; organization_name: string; assignee_identity_id: string; assignee_email: string; kind: "concierge" | "mentor"; assigned_at: string };
type Operator = { email: string; identity_id: string; roles: InternalRole[] };

export function OpsPortfolioConsole({ organizations, operators, portfolios, managed, globalMentor, roles }: { organizations: { organization_id: string; organization_name: string }[]; operators: Operator[]; portfolios: Portfolio[]; managed: ManagedPortfolio[]; globalMentor: { organization_id: string; organization_name: string; active_cycle_title: string | null; active_cycle_ends_on: string | null; next_action_label: string | null; available_mission_count: number; approved_milestone_count: number }[]; roles: InternalRole[] }) {
  const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false);
  const canManage = roles.includes("admin");
  async function submit(body: object) { setPending(true); setMessage(null); try { const response = await fetch("/api/ops/portfolios", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error("request_failed"); setMessage("Carteira registrada com auditoria. Atualize a página para consultar o estado atual."); } catch { setMessage("Não foi possível alterar a carteira."); } finally { setPending(false); } }
  function assign(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "assign", organizationId: form.get("organizationId"), assigneeIdentityId: form.get("assigneeIdentityId"), kind: form.get("kind"), reason: form.get("reason") || null }); }
  return <section className="ops-finance"><header><p className="eyebrow">Acompanhamento do membro</p><h2>{canManage ? "Distribuição de carteiras" : roles.includes("mentor") ? "Comunidade acompanhada" : "Minha carteira"}</h2><p className="summary">Mentores acompanham todos os membros. A Concierge atua somente sobre sua carteira atribuída, respeitando a capacidade definida pela operação. Conversas do TutorIA, anexos, finanças e dados comerciais permanecem isolados.</p></header>
    {canManage && <details><summary>+ Atribuir carteira</summary><form className="auth-form" onSubmit={assign}><label>Organização<select name="organizationId" required>{organizations.map((organization) => <option key={organization.organization_id} value={organization.organization_id}>{organization.organization_name}</option>)}</select></label><label>Função<select name="kind" required defaultValue="concierge"><option value="concierge">Concierge</option><option value="mentor">Mentor</option></select></label><label>Pessoa interna<select name="assigneeIdentityId" required>{operators.filter((operator) => operator.roles.includes("concierge") || operator.roles.includes("mentor")).map((operator) => <option key={operator.identity_id} value={operator.identity_id}>{operator.email} · {operator.roles.filter((role) => role === "concierge" || role === "mentor").join(", ")}</option>)}</select></label><label>Motivo operacional<input name="reason" minLength={3} maxLength={500} required /></label><button disabled={pending || !organizations.length}>Atribuir</button></form></details>}
    {canManage && <section className="ops-finance-list"><h3>Carteiras ativas</h3>{managed.length ? <ul>{managed.map((portfolio) => <li key={portfolio.assignment_id}><strong>{portfolio.organization_name}</strong> · {portfolio.kind === "mentor" ? "Mentor" : "Concierge"}<br />{portfolio.assignee_email}<br /><button className="button-quiet" type="button" disabled={pending} onClick={() => void submit({ action: "revoke", assignmentId: portfolio.assignment_id })}>Revogar carteira</button></li>)}</ul> : <p className="feedback">Nenhuma carteira atribuída.</p>}</section>}
    {!canManage && roles.includes("mentor") && <section className="ops-finance-list"><h3>Comunidade acompanhada</h3>{globalMentor.length ? <ul>{globalMentor.map((member) => <li key={member.organization_id}><strong>{member.organization_name}</strong><br />{member.active_cycle_title ?? "Sem ciclo ativo"}{member.next_action_label ? ` · Próxima ação: ${member.next_action_label}` : ""}<br />{member.approved_milestone_count} marco(s) aprovado(s)</li>)}</ul> : <p className="feedback">Nenhuma organização disponível para acompanhamento.</p>}</section>}
    {!canManage && !roles.includes("mentor") && <section className="ops-finance-list"><h3>Minha carteira</h3>{portfolios.length ? <ul>{portfolios.map((portfolio) => <li key={portfolio.assignment_id}><strong>{portfolio.organization_name}</strong><br />{portfolio.onboarding_pending_enrollments} pendência(s) de matrícula</li>)}</ul> : <p className="feedback">Nenhuma empresa está atribuída à sua carteira.</p>}</section>}
    {message && <p className="feedback" role="status">{message}</p>}
  </section>;
}
