-- Keep public RPCs thin. Privileged domain logic lives outside the exposed API schema.
alter function public.confirm_priority(uuid, text) set schema private;
alter function public.provision_cycle_missions(uuid) set schema private;
alter function public.save_diagnostic_responses(uuid, jsonb) set schema private;
alter function public.save_mission_implementation(uuid, text, date, boolean) set schema private;
alter function public.save_mission_tool_draft(uuid, jsonb) set schema private;
alter function public.start_cycle(uuid) set schema private;
alter function public.start_diagnostic(uuid) set schema private;
alter function public.start_diagnostic_episode(uuid, text, uuid, date) set schema private;
alter function public.submit_diagnostic(uuid) set schema private;
alter function public.submit_evidence_revision(uuid, text, text, date) set schema private;
alter function public.submit_mission_evidence_and_advance(uuid, text, text, date) set schema private;

create function public.confirm_priority(target_execution_id uuid, priority_rationale text) returns uuid language sql security invoker set search_path = '' as $$ select private.confirm_priority($1, $2) $$;
create function public.provision_cycle_missions(target_cycle_id uuid) returns integer language sql security invoker set search_path = '' as $$ select private.provision_cycle_missions($1) $$;
create function public.save_diagnostic_responses(target_execution_id uuid, submitted_answers jsonb) returns void language sql security invoker set search_path = '' as $$ select private.save_diagnostic_responses($1, $2) $$;
create function public.save_mission_implementation(target_mission_id uuid, implementation_summary text, implementation_date date, confirm_implementation boolean default false) returns uuid language sql security invoker set search_path = '' as $$ select private.save_mission_implementation($1, $2, $3, $4) $$;
create function public.save_mission_tool_draft(target_mission_id uuid, submitted_payload jsonb) returns uuid language sql security invoker set search_path = '' as $$ select private.save_mission_tool_draft($1, $2) $$;
create function public.start_cycle(target_priority_id uuid) returns uuid language sql security invoker set search_path = '' as $$ select private.start_cycle($1) $$;
create function public.start_diagnostic(target_revision_id uuid) returns uuid language sql security invoker set search_path = '' as $$ select private.start_diagnostic($1) $$;
create function public.start_diagnostic_episode(target_revision_id uuid, target_episode_type text, target_cycle_id uuid default null, target_effective_on date default current_date) returns uuid language sql security invoker set search_path = '' as $$ select private.start_diagnostic_episode($1, $2, $3, $4) $$;
create function public.submit_diagnostic(target_execution_id uuid) returns jsonb language sql security invoker set search_path = '' as $$ select private.submit_diagnostic($1) $$;
create function public.submit_evidence_revision(target_evidence_id uuid, submitted_evidence_type text, evidence_description text, evidence_date date) returns uuid language sql security invoker set search_path = '' as $$ select private.submit_evidence_revision($1, $2, $3, $4) $$;
create function public.submit_mission_evidence_and_advance(target_mission_id uuid, submitted_evidence_type text, evidence_description text, evidence_date date) returns jsonb language sql security invoker set search_path = '' as $$ select private.submit_mission_evidence_and_advance($1, $2, $3, $4) $$;

revoke all on function private.confirm_priority(uuid, text) from public, anon;
revoke all on function private.provision_cycle_missions(uuid) from public, anon;
revoke all on function private.save_diagnostic_responses(uuid, jsonb) from public, anon;
revoke all on function private.save_mission_implementation(uuid, text, date, boolean) from public, anon;
revoke all on function private.save_mission_tool_draft(uuid, jsonb) from public, anon;
revoke all on function private.start_cycle(uuid) from public, anon;
revoke all on function private.start_diagnostic(uuid) from public, anon;
revoke all on function private.start_diagnostic_episode(uuid, text, uuid, date) from public, anon;
revoke all on function private.submit_diagnostic(uuid) from public, anon;
revoke all on function private.submit_evidence_revision(uuid, text, text, date) from public, anon;
revoke all on function private.submit_mission_evidence_and_advance(uuid, text, text, date) from public, anon;
grant execute on function private.confirm_priority(uuid, text) to authenticated;
grant execute on function private.provision_cycle_missions(uuid) to authenticated;
grant execute on function private.save_diagnostic_responses(uuid, jsonb) to authenticated;
grant execute on function private.save_mission_implementation(uuid, text, date, boolean) to authenticated;
grant execute on function private.save_mission_tool_draft(uuid, jsonb) to authenticated;
grant execute on function private.start_cycle(uuid) to authenticated;
grant execute on function private.start_diagnostic(uuid) to authenticated;
grant execute on function private.start_diagnostic_episode(uuid, text, uuid, date) to authenticated;
grant execute on function private.submit_diagnostic(uuid) to authenticated;
grant execute on function private.submit_evidence_revision(uuid, text, text, date) to authenticated;
grant execute on function private.submit_mission_evidence_and_advance(uuid, text, text, date) to authenticated;

revoke all on function public.confirm_priority(uuid, text) from public, anon;
revoke all on function public.provision_cycle_missions(uuid) from public, anon;
revoke all on function public.save_diagnostic_responses(uuid, jsonb) from public, anon;
revoke all on function public.save_mission_implementation(uuid, text, date, boolean) from public, anon;
revoke all on function public.save_mission_tool_draft(uuid, jsonb) from public, anon;
revoke all on function public.start_cycle(uuid) from public, anon;
revoke all on function public.start_diagnostic(uuid) from public, anon;
revoke all on function public.start_diagnostic_episode(uuid, text, uuid, date) from public, anon;
revoke all on function public.submit_diagnostic(uuid) from public, anon;
revoke all on function public.submit_evidence_revision(uuid, text, text, date) from public, anon;
revoke all on function public.submit_mission_evidence_and_advance(uuid, text, text, date) from public, anon;
grant execute on function public.confirm_priority(uuid, text) to authenticated;
grant execute on function public.provision_cycle_missions(uuid) to authenticated;
grant execute on function public.save_diagnostic_responses(uuid, jsonb) to authenticated;
grant execute on function public.save_mission_implementation(uuid, text, date, boolean) to authenticated;
grant execute on function public.save_mission_tool_draft(uuid, jsonb) to authenticated;
grant execute on function public.start_cycle(uuid) to authenticated;
grant execute on function public.start_diagnostic(uuid) to authenticated;
grant execute on function public.start_diagnostic_episode(uuid, text, uuid, date) to authenticated;
grant execute on function public.submit_diagnostic(uuid) to authenticated;
grant execute on function public.submit_evidence_revision(uuid, text, text, date) to authenticated;
grant execute on function public.submit_mission_evidence_and_advance(uuid, text, text, date) to authenticated;
